#!/bin/sh

if [ -f /media/wpa_supplicant.conf ]; then
  ip link set wlan0 up
  wpa_supplicant -B -iwlan0 -c/media/wpa_supplicant.conf -Dwext
  udhcpc -i wlan0
else
  echo "WiFi not yet configured... skiped"
fi
