#!/bin/sh

case "$1" in
        start|"")
                /bin/fanboy &
                ;;
        stop)
		curl http://127.0.0.1/stop
                 ;;
        *)
                echo "Usage: fanboy {start|stop}" >&2
                exit 1
                ;;
esac

